# Generated by Django 3.2.7 on 2024-05-27 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+233 8603555', max_length=30, region=None, verbose_name='Phone Number')),
                ('about_me', models.TextField(default='Say something about your self', verbose_name='About me')),
                ('profile_photo', models.ImageField(default='/profile_photo.png', upload_to='', verbose_name='Profile Photo')),
                ('category', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Kids', 'Kids'), ('Other', 'Other')], max_length=6, verbose_name='Category')),
                ('country', django_countries.fields.CountryField(default='GH', max_length=2, verbose_name='Country')),
                ('subscribed', models.BooleanField(default=False, help_text='Upgraded user', verbose_name='Subscribed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
